# Настойка settings.py
GLOBAL:
  SECRET_KEY: Секретный ключ
  DEBUG: !!bool true
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: "Путь к sqlite3.db"
  ALLOWED_HOSTS:
    - 127.0.0.1
  STATIC_DIR: './STATIC_ROOT'
  DEBUG_PROPAGATE_EXCEPTIONS: !!bool false